"""empty message

Revision ID: eec9eb9d0f28
Revises: 1f3273c7b850
Create Date: 2017-04-25 12:08:51.359220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec9eb9d0f28'
down_revision = '1f3273c7b850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_nodes_create_time'), 'nodes', ['create_time'], unique=False)
    op.add_column('posts', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'count')
    op.drop_index(op.f('ix_nodes_create_time'), table_name='nodes')
    # ### end Alembic commands ###
